server:
  port: 8095
  servlet:
    context-path: /appointment
#  ssl:
#
#    key-alias: selfsigned_localhost_sslserver
#    key-store: classpath:ssl-server.jks
#    key-store-type: JKS
#    key-password: changeit
spring:
  application:
    name: appointment-service 
  

  datasource:
    url: jdbc:mysql://db.ccb27u4ngh0j.ap-south-1.rds.amazonaws.com:3306/AppointmentServicedatabase?createDatabaseIfNotExist=true
    username: admin
    password: qwerty12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
     ddl-auto: update
    properties:
     hibernate:
       database-platform: org.hibernate.dialect.MySQL8Dialect


swagger:
  url: https://virtusa-appointment.learn.skillassure.com/appointment

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 106.51.36.182

logging:
  file:
    name: inventory.log`
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    '[org.springframework.web]': INFO
    '[com.ros.inventory]': DEBUG
    '[org.hibernate]': INFO
