server:
  port: 8069
  servlet:
    context-path: /doctor
  ssl:

    key-alias: selfsigned_localhost_sslserver
    key-store: classpath:ssl-server.jks
    key-store-type: JKS
    key-password: changeit 

spring:
  application:
    name: doctor-service 

  datasource:
    url: jdbc:mysql://localhost:3306/doctordetails?createDatabaseIfNotExist=true
    #url: jdbc:mysql://db.ccb27u4ngh0j.ap-south-1.rds.amazonaws.com:3306/DoctorServiceDatabase?createDatabaseIfNotExist=true
    #username: admin
    #password: qwerty12345
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
     ddl-auto: update
    properties:
     hibernate:
            database-platform: org.hibernate.dialect.MySQL8Dialect
           
swagger:
  url: 
    #productionURL: https://virtusa-doctor.learn.skillassure.com/doctor
     localURL: https://localhost:${server.port}/doctor
      
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
logging:
  file:
    name: inventory.log
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    '[org.springframework.web]': INFO
    '[com.ros.inventory]': DEBUG
    '[org.hibernate]': INFO
